### PR TITLE
README: Add "Unmaintained" banner

### LINKED ISSUE #29: Unused/Unmaintained?
It looks like this project is somewhat unmaintained and no longer used by Ember CLI itself (see #28). If that is indeed the case should we put a note about that in the README file?

/cc @rwjblue @stefanpenner

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #29 

/cc @stefanpenner

### CODE REVIEW

**Comment by stefanpenner** [comment]
👍

**Comment by stefanpenner** [comment]
should we release a maintenance release to include this in the readme on NPM?

**Comment by Turbo87** [comment]
I tend to ignore the readmes on NPM, but feel free to do that.

**Comment by stefanpenner** [comment]
> I tend to ignore the readmes on NPM, but feel free to do that.

kk

**Comment by stefanpenner** [comment]
complete, i figure we can catch those who use the npm readme as a source of truth.

```
➜  broccoli-es6modules git:(master) git tag v1.2.3
➜  broccoli-es6modules git:(master) git push origin v1.2.3
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:ember-cli/broccoli-es6modules.git
 * [new tag]         v1.2.3 -> v1.2.3
➜  broccoli-es6modules git:(master) npm publish
+ broccoli-es6modules@1.2.3
```

**Pull request merged**
